### PR TITLE
Add endpoint_url to config

### PR DESCRIPTION
**Pull request by alxpy**
[boto3 docs reference](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html?highlight=endpoint_url#boto3.session.Session.resource)

### CODE REVIEW

**Comment by alxpy** [comment]
@jonls hi! what do you think about this changes?

**Comment by alxpy** [comment]
> Waiting for status to be reported

@jonls can you please restart `travis-ci`?

**Comment by jonls** [comment]
@alxpy I've restarted Travis CI but there might be a build error here that's unrelated to your change. I'm not sure yet. I'll take a look into it later.

**Comment by alxpy** [comment]
New  PR — https://github.com/jonls/s3-deploy-website/pull/20

**Pull request closed without merging**
