### PR TITLE
Add endpoint_url to config

### PR DESCRIPTION
**Pull request by oleksandr-kuzmenko**
[boto3 docs reference](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html?highlight=endpoint_url#boto3.session.Session.resource)

Ref: https://github.com/jonls/s3-deploy-website/pull/20

### CODE REVIEW

**Comment by alxpy** [comment]
@jonls
now CI works, but tests fails

**Comment by jonls** [comment]
@alxpy The setup for Travis CI was broken. I've fixed this in #22. Can you please rebase on master?

**Comment by alxpy** [comment]
@jonls done

**Comment by jonls** [comment]
Thanks! Merged in #25

**Pull request closed without merging**
