### PR TITLE
Support regular expressions for cache rules

### PR DESCRIPTION
**Pull request by felixbuenemann**
This extends the cache_rules matching to detect all match values that start with `^` or end with `$` as regular expressions. All other values are treated as globs like before.

This allows to do advanced matching like in the following example:

```yaml
cache_rules:
  - match: '^_nuxt/.*[^/]+\.(?:[0-9a-f]{7}|[0-9a-f]{20}|[0-9a-f]{32})\.[a-z0-9.]{1,6}$'
    cache_control: 'public, max-age=31536000, immutable'

  - match: '(?:[A-Z]+|[^/]+\.html)$'
    cache_control: 'public, max-age=7200, s-maxage=86400'

  - match: '[^/]+\.[a-z0-9.]{1,6}$'
    cache_control: 'public, max-age=86400, s-maxage=2592000'
```

### CODE REVIEW

**Comment by felixbuenemann** [comment]
Test failures are unrelated:

```
s3_deploy/config.py:27:13: E722 do not use bare except'
```

**Comment by jonls** [comment]
Thanks, looks good. Can you rebase this? I'm thinking that maybe it would be better to mark regexp match entries explicitly e.g.

``` yaml
cache_rules:
  - match:
      regexp: '^_nuxt/.*[^/]+\.(?:[0-9a-f]{7}|[0-9a-f]{20}|[0-9a-f]{32})\.[a-z0-9.]{1,6}$'
    cache_control: '...'
```
or
``` yaml
cache_rules:
  - match: '^_nuxt/.*[^/]+\.(?:[0-9a-f]{7}|[0-9a-f]{20}|[0-9a-f]{32})\.[a-z0-9.]{1,6}$'
    regexp: true
    cache_control: '...'
```

what do you think?

**Comment by felixbuenemann** [comment]
I thought about the second variant with the boolean flag first, but decided it was very unlikely that a user actually wanted to match, but if you prefer I can add the flag.

I don't like the first variant, because the nesting differs between the two types (wildcard/regex).

**Comment by felixbuenemann** [comment]
Argh, looks like GitHub's "Update Branch" does a merge instead of a rebase, I'll rebase myself to get rid of the merge commit.

**Comment by jonls** [comment]
Some other options
```
cache_rules:
  - match: '^_nuxt/.*[^/]+\.(?:[0-9a-f]{7}|[0-9a-f]{20}|[0-9a-f]{32})\.[a-z0-9.]{1,6}$'
    match_type: regexp
    cache_control: '...'
```

```
cache_rules:
  - match_regexp: '^_nuxt/.*[^/]+\.(?:[0-9a-f]{7}|[0-9a-f]{20}|[0-9a-f]{32})\.[a-z0-9.]{1,6}$'
    cache_control: '...'
```
?

In any case I think this feature should also be mentioned in the README.

**Comment by jonls** [comment]
Merged in #23.

**Pull request closed without merging**
